// Generated by tools/generate_rtl_functions.py; do not edit by hand.
// AES S-box SLPs: NIST Circuits revision 4e23832e62f490aeffd8770b1285d99056b5f8bf.

function automatic [7:0] aes_sbox(input [7:0] value);
  reg [104:0] t;
  reg [7:0] s;
  begin
    t[0] = value[4] ^ value[2];
    t[1] = value[7] ^ value[1];
    t[2] = value[7] ^ value[4];
    t[3] = value[7] ^ value[2];
    t[4] = value[6] ^ value[5];
    t[5] = t[4] ^ value[0];
    t[6] = t[5] ^ value[4];
    t[7] = t[1] ^ t[0];
    t[8] = t[5] ^ value[7];
    t[9] = t[5] ^ value[1];
    t[10] = t[9] ^ t[3];
    t[11] = value[3] ^ t[7];
    t[12] = t[11] ^ value[2];
    t[13] = t[11] ^ value[6];
    t[14] = t[12] ^ value[0];
    t[15] = t[12] ^ t[4];
    t[16] = t[13] ^ t[2];
    t[17] = value[0] ^ t[16];
    t[18] = t[15] ^ t[16];
    t[19] = t[15] ^ t[3];
    t[20] = t[4] ^ t[16];
    t[21] = t[1] ^ t[20];
    t[22] = value[7] ^ t[20];
    t[23] = t[7] & t[12];
    t[24] = t[10] & t[14];
    t[25] = t[24] ^ t[23];
    t[26] = t[6] & value[0];
    t[27] = t[26] ^ t[23];
    t[28] = t[1] & t[20];
    t[29] = t[9] & t[5];
    t[30] = t[29] ^ t[28];
    t[31] = t[8] & t[17];
    t[32] = t[31] ^ t[28];
    t[33] = t[2] & t[16];
    t[34] = t[0] & t[18];
    t[35] = t[34] ^ t[33];
    t[36] = t[3] & t[15];
    t[37] = t[36] ^ t[33];
    t[38] = t[25] ^ t[13];
    t[39] = t[27] ^ t[37];
    t[40] = t[30] ^ t[35];
    t[41] = t[32] ^ t[37];
    t[42] = t[38] ^ t[35];
    t[43] = t[39] ^ t[19];
    t[44] = t[40] ^ t[21];
    t[45] = t[41] ^ t[22];
    t[46] = t[42] ^ t[43];
    t[47] = t[42] & t[44];
    t[48] = t[45] ^ t[47];
    t[49] = t[46] & t[48];
    t[50] = t[49] ^ t[43];
    t[51] = t[44] ^ t[45];
    t[52] = t[43] ^ t[47];
    t[53] = t[52] & t[51];
    t[54] = t[53] ^ t[45];
    t[55] = t[44] ^ t[54];
    t[56] = t[48] ^ t[54];
    t[57] = t[45] & t[56];
    t[58] = t[57] ^ t[55];
    t[59] = t[48] ^ t[57];
    t[60] = t[50] & t[59];
    t[61] = t[46] ^ t[60];
    t[62] = t[61] ^ t[58];
    t[63] = t[50] ^ t[54];
    t[64] = t[50] ^ t[61];
    t[65] = t[54] ^ t[58];
    t[66] = t[63] ^ t[62];
    t[67] = t[65] & t[12];
    t[68] = t[58] & t[14];
    t[69] = t[54] & value[0];
    t[70] = t[64] & t[20];
    t[71] = t[61] & t[5];
    t[72] = t[50] & t[17];
    t[73] = t[63] & t[16];
    t[74] = t[66] & t[18];
    t[75] = t[62] & t[15];
    t[76] = t[65] & t[7];
    t[77] = t[58] & t[10];
    t[78] = t[54] & t[6];
    t[79] = t[64] & t[1];
    t[80] = t[61] & t[9];
    t[81] = t[50] & t[8];
    t[82] = t[63] & t[2];
    t[83] = t[66] & t[0];
    t[84] = t[62] & t[3];
    t[85] = t[82] ^ t[83];
    t[86] = t[77] ^ t[85];
    t[87] = t[76] ^ t[86];
    t[88] = t[67] ^ t[69];
    t[89] = t[68] ^ t[67];
    t[90] = t[70] ^ t[71];
    t[91] = t[79] ^ t[88];
    t[92] = t[74] ^ t[90];
    t[93] = t[75] ^ t[91];
    t[94] = t[92] ^ t[93];
    t[95] = t[90] ^ t[89];
    t[96] = t[70] ^ t[72];
    t[97] = t[80] ^ t[85];
    t[98] = t[88] ^ t[96];
    s[4] = t[87] ^ t[95];
    t[99] = t[73] ^ t[92];
    t[100] = t[81] ^ t[94];
    t[101] = t[97] ^ t[98];
    s[0] = ~(t[79] ^ t[101]);
    t[102] = t[82] ^ t[99];
    t[103] = t[86] ^ t[78];
    s[7] = t[87] ^ t[99];
    s[1] = ~(t[94] ^ t[101]);
    s[3] = t[98] ^ s[4];
    s[6] = ~(s[4] ^ t[99]);
    t[104] = t[100] ^ t[102];
    s[5] = ~(t[104] ^ t[84]);
    s[2] = t[103] ^ t[100];
    aes_sbox = s;
  end
endfunction
function automatic [7:0] aes_inv_sbox(input [7:0] value);
  reg [112:0] t;
  reg [7:0] s;
  begin
    t[0] = value[7] ^ value[4];
    t[1] = ~(value[6] ^ value[4]);
    t[2] = value[7] ^ t[1];
    t[3] = value[1] ^ value[0];
    t[4] = t[1] ^ t[3];
    t[5] = ~(value[5] ^ t[4]);
    t[6] = value[4] ^ value[3];
    t[7] = ~(value[0] ^ t[6]);
    t[8] = t[4] ^ t[6];
    t[9] = ~(value[7] ^ value[5]);
    t[10] = value[2] ^ t[9];
    t[11] = t[0] ^ t[1];
    t[12] = t[4] ^ t[8];
    t[13] = t[2] ^ t[7];
    t[14] = t[10] ^ t[5];
    t[15] = t[0] ^ t[4];
    t[16] = t[1] ^ t[8];
    t[17] = t[12] ^ t[11];
    t[18] = t[2] ^ t[10];
    t[19] = t[7] ^ t[5];
    t[20] = t[14] ^ t[13];
    t[21] = t[12] ^ t[14];
    t[22] = t[16] ^ t[19];
    t[23] = t[8] ^ t[5];
    t[24] = t[11] ^ t[13];
    t[25] = t[15] & t[18];
    t[26] = t[0] & t[2];
    t[27] = t[21] ^ t[25];
    t[28] = t[4] & t[10];
    t[29] = t[28] ^ t[25];
    t[30] = t[16] & t[19];
    t[31] = t[1] & t[7];
    t[32] = t[22] ^ t[30];
    t[33] = t[8] & t[5];
    t[34] = t[33] ^ t[30];
    t[35] = t[12] & t[14];
    t[36] = t[17] & t[20];
    t[37] = t[36] ^ t[35];
    t[38] = t[11] & t[13];
    t[39] = t[38] ^ t[35];
    t[40] = t[27] ^ t[26];
    t[41] = t[29] ^ t[24];
    t[42] = t[32] ^ t[31];
    t[43] = t[34] ^ t[39];
    t[44] = t[40] ^ t[37];
    t[45] = t[41] ^ t[39];
    t[46] = t[42] ^ t[37];
    t[47] = t[43] ^ t[23];
    t[48] = t[46] ^ t[47];
    t[49] = t[46] & t[44];
    t[50] = t[45] ^ t[49];
    t[51] = t[44] ^ t[45];
    t[52] = t[47] ^ t[49];
    t[53] = t[52] & t[51];
    t[54] = t[50] & t[48];
    t[55] = t[47] ^ t[54];
    t[56] = t[45] ^ t[53];
    t[57] = t[44] & t[47];
    t[58] = t[51] & t[57];
    t[59] = t[51] ^ t[49];
    t[60] = t[58] ^ t[59];
    t[61] = t[45] & t[46];
    t[62] = t[48] & t[61];
    t[63] = t[48] ^ t[49];
    t[64] = t[62] ^ t[63];
    t[65] = t[60] ^ t[64];
    t[66] = t[56] ^ t[55];
    t[67] = t[56] ^ t[60];
    t[68] = t[55] ^ t[64];
    t[69] = t[66] ^ t[65];
    t[70] = t[68] & t[18];
    t[71] = t[64] & t[2];
    t[72] = t[55] & t[10];
    t[73] = t[67] & t[19];
    t[74] = t[60] & t[7];
    t[75] = t[56] & t[5];
    t[76] = t[66] & t[14];
    t[77] = t[69] & t[20];
    t[78] = t[65] & t[13];
    t[79] = t[68] & t[15];
    t[80] = t[64] & t[0];
    t[81] = t[55] & t[4];
    t[82] = t[67] & t[16];
    t[83] = t[60] & t[1];
    t[84] = t[56] & t[8];
    t[85] = t[66] & t[12];
    t[86] = t[69] & t[17];
    t[87] = t[65] & t[11];
    t[88] = t[71] ^ t[70];
    t[89] = t[72] ^ t[70];
    t[90] = t[74] ^ t[73];
    t[91] = t[75] ^ t[73];
    t[92] = t[77] ^ t[76];
    t[93] = t[78] ^ t[76];
    t[94] = t[88] ^ t[92];
    t[95] = t[89] ^ t[93];
    t[96] = t[90] ^ t[92];
    t[97] = t[91] ^ t[93];
    t[98] = t[80] ^ t[79];
    t[99] = t[81] ^ t[79];
    t[100] = t[83] ^ t[82];
    t[101] = t[84] ^ t[82];
    t[102] = t[86] ^ t[85];
    t[103] = t[87] ^ t[85];
    t[104] = t[98] ^ t[102];
    s[0] = t[99] ^ t[103];
    t[105] = t[100] ^ t[102];
    t[106] = t[101] ^ t[103];
    s[4] = t[95] ^ t[105];
    s[1] = t[96] ^ t[105];
    s[7] = t[97] ^ t[105];
    t[107] = t[94] ^ t[96];
    s[2] = s[7] ^ t[107];
    t[108] = t[104] ^ t[106];
    t[109] = t[107] ^ t[108];
    s[6] = s[4] ^ t[109];
    t[110] = t[95] ^ s[0];
    s[5] = t[109] ^ t[110];
    t[111] = t[94] ^ t[104];
    t[112] = s[2] ^ t[110];
    s[3] = t[111] ^ t[112];
    aes_inv_sbox = s;
  end
endfunction
function automatic [7:0] aes_xtime(input [7:0] value);
  aes_xtime = {value[6:0], 1'b0} ^ (8'h1b & {8{value[7]}});
endfunction

function automatic [7:0] aes_gf_mul(input [7:0] left, input [7:0] right);
  reg [7:0] x2;
  reg [7:0] x4;
  reg [7:0] x8;
  begin
    x2 = aes_xtime(right);
    x4 = aes_xtime(x2);
    x8 = aes_xtime(x4);
    case (left)
      8'h01: aes_gf_mul = right;
      8'h02: aes_gf_mul = x2;
      8'h03: aes_gf_mul = x2 ^ right;
      8'h09: aes_gf_mul = x8 ^ right;
      8'h0b: aes_gf_mul = x8 ^ x2 ^ right;
      8'h0d: aes_gf_mul = x8 ^ x4 ^ right;
      8'h0e: aes_gf_mul = x8 ^ x4 ^ x2;
      default: aes_gf_mul = 8'h00;
    endcase
  end
endfunction

function automatic [127:0] aes_sub_bytes(input [127:0] state);
  integer i;
  begin
    for (i = 0; i < 16; i = i + 1)
      aes_sub_bytes[127 - i*8 -: 8] = aes_sbox(state[127 - i*8 -: 8]);
  end
endfunction

function automatic [127:0] aes_inv_sub_bytes(input [127:0] state);
  integer i;
  begin
    for (i = 0; i < 16; i = i + 1)
      aes_inv_sub_bytes[127 - i*8 -: 8] = aes_inv_sbox(state[127 - i*8 -: 8]);
  end
endfunction

function automatic [127:0] aes_shift_rows(input [127:0] state);
  integer row;
  integer column;
  integer source_column;
  begin
    for (column = 0; column < 4; column = column + 1)
      for (row = 0; row < 4; row = row + 1) begin
        source_column = (column + row) % 4;
        aes_shift_rows[127 - (4*column + row)*8 -: 8] = state[127 - (4*source_column + row)*8 -: 8];
      end
  end
endfunction

function automatic [127:0] aes_inv_shift_rows(input [127:0] state);
  integer row;
  integer column;
  integer source_column;
  begin
    for (column = 0; column < 4; column = column + 1)
      for (row = 0; row < 4; row = row + 1) begin
        source_column = (column - row + 4) % 4;
        aes_inv_shift_rows[127 - (4*column + row)*8 -: 8] = state[127 - (4*source_column + row)*8 -: 8];
      end
  end
endfunction

function automatic [127:0] aes_mix_columns(input [127:0] state);
  reg [7:0] a0;
  reg [7:0] a1;
  reg [7:0] a2;
  reg [7:0] a3;
  integer column;
  begin
    for (column = 0; column < 4; column = column + 1) begin
      a0 = state[127 - (4*column + 0)*8 -: 8];
      a1 = state[127 - (4*column + 1)*8 -: 8];
      a2 = state[127 - (4*column + 2)*8 -: 8];
      a3 = state[127 - (4*column + 3)*8 -: 8];
      aes_mix_columns[127 - (4*column + 0)*8 -: 8] = aes_gf_mul(8'h02, a0) ^ aes_gf_mul(8'h03, a1) ^ a2 ^ a3;
      aes_mix_columns[127 - (4*column + 1)*8 -: 8] = a0 ^ aes_gf_mul(8'h02, a1) ^ aes_gf_mul(8'h03, a2) ^ a3;
      aes_mix_columns[127 - (4*column + 2)*8 -: 8] = a0 ^ a1 ^ aes_gf_mul(8'h02, a2) ^ aes_gf_mul(8'h03, a3);
      aes_mix_columns[127 - (4*column + 3)*8 -: 8] = aes_gf_mul(8'h03, a0) ^ a1 ^ a2 ^ aes_gf_mul(8'h02, a3);
    end
  end
endfunction

function automatic [127:0] aes_inv_mix_columns(input [127:0] state);
  reg [7:0] a0;
  reg [7:0] a1;
  reg [7:0] a2;
  reg [7:0] a3;
  integer column;
  begin
    for (column = 0; column < 4; column = column + 1) begin
      a0 = state[127 - (4*column + 0)*8 -: 8];
      a1 = state[127 - (4*column + 1)*8 -: 8];
      a2 = state[127 - (4*column + 2)*8 -: 8];
      a3 = state[127 - (4*column + 3)*8 -: 8];
      aes_inv_mix_columns[127 - (4*column + 0)*8 -: 8] = aes_gf_mul(8'h0e, a0) ^ aes_gf_mul(8'h0b, a1) ^ aes_gf_mul(8'h0d, a2) ^ aes_gf_mul(8'h09, a3);
      aes_inv_mix_columns[127 - (4*column + 1)*8 -: 8] = aes_gf_mul(8'h09, a0) ^ aes_gf_mul(8'h0e, a1) ^ aes_gf_mul(8'h0b, a2) ^ aes_gf_mul(8'h0d, a3);
      aes_inv_mix_columns[127 - (4*column + 2)*8 -: 8] = aes_gf_mul(8'h0d, a0) ^ aes_gf_mul(8'h09, a1) ^ aes_gf_mul(8'h0e, a2) ^ aes_gf_mul(8'h0b, a3);
      aes_inv_mix_columns[127 - (4*column + 3)*8 -: 8] = aes_gf_mul(8'h0b, a0) ^ aes_gf_mul(8'h0d, a1) ^ aes_gf_mul(8'h09, a2) ^ aes_gf_mul(8'h0e, a3);
    end
  end
endfunction

function automatic [127:0] aes_round(input [127:0] state, input [127:0] round_key);
  aes_round = aes_mix_columns(aes_shift_rows(aes_sub_bytes(state))) ^ round_key;
endfunction

function automatic [127:0] aes_final_round(input [127:0] state, input [127:0] round_key);
  aes_final_round = aes_shift_rows(aes_sub_bytes(state)) ^ round_key;
endfunction

function automatic [127:0] aes_inv_round(input [127:0] state, input [127:0] round_key);
  aes_inv_round = aes_inv_mix_columns(aes_inv_sub_bytes(aes_inv_shift_rows(state)) ^ round_key);
endfunction

function automatic [127:0] aes_inv_final_round(input [127:0] state, input [127:0] round_key);
  aes_inv_final_round = aes_inv_sub_bytes(aes_inv_shift_rows(state)) ^ round_key;
endfunction

function automatic [7:0] aes_rcon(input [3:0] pair_index);
  begin
    case (pair_index)
      4'd1: aes_rcon = 8'h01;
      4'd2: aes_rcon = 8'h02;
      4'd3: aes_rcon = 8'h04;
      4'd4: aes_rcon = 8'h08;
      4'd5: aes_rcon = 8'h10;
      4'd6: aes_rcon = 8'h20;
      4'd7: aes_rcon = 8'h40;
      default: aes_rcon = 8'h00;
    endcase
  end
endfunction

function automatic [31:0] aes_sub_word(input [31:0] word);
  aes_sub_word = {aes_sbox(word[31:24]), aes_sbox(word[23:16]), aes_sbox(word[15:8]), aes_sbox(word[7:0])};
endfunction

function automatic [255:0] aes_next_key_pair(input [255:0] current, input [3:0] pair_index);
  reg [31:0] w0;
  reg [31:0] w1;
  reg [31:0] w2;
  reg [31:0] w3;
  reg [31:0] w4;
  reg [31:0] w5;
  reg [31:0] w6;
  reg [31:0] w7;
  reg [31:0] n0;
  reg [31:0] n1;
  reg [31:0] n2;
  reg [31:0] n3;
  reg [31:0] n4;
  reg [31:0] n5;
  reg [31:0] n6;
  reg [31:0] n7;
  begin
    {w0, w1, w2, w3, w4, w5, w6, w7} = current;
    n0 = w0 ^ aes_sub_word({w7[23:0], w7[31:24]}) ^ {aes_rcon(pair_index), 24'h0};
    n1 = w1 ^ n0;
    n2 = w2 ^ n1;
    n3 = w3 ^ n2;
    n4 = w4 ^ aes_sub_word(n3);
    n5 = w5 ^ n4;
    n6 = w6 ^ n5;
    n7 = w7 ^ n6;
    aes_next_key_pair = {n0, n1, n2, n3, n4, n5, n6, n7};
  end
endfunction

