#!/usr/bin/env python3
"""Generate small C++ headers from the committed JSON corpora."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "reference"))

from aes_gcm import encrypt, expand_key


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path, default=ROOT / "tests")
    args = parser.parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    nist = json.loads((ROOT / "vectors" / "nist_subset.json").read_text())
    generated = json.loads((ROOT / "vectors" / "generated.json").read_text())
    output = args.output_dir / "primitive_vectors.h"
    lines = [
        "// Generated by tools/generate_harness_vectors.py; do not edit.",
        "#pragma once",
        "struct PrimitiveVector { const char *key; const char *plaintext; const char *ciphertext; const char *round_keys; };",
        "static const PrimitiveVector kPrimitiveVectors[] = {",
    ]
    for item in nist["aes_block"]:
        round_keys = "".join(key.hex() for key in expand_key(bytes.fromhex(item["key"])))
        lines.append(
            f'    {{"{item["key"]}", "{item["plaintext"]}", "{item["ciphertext"]}", "{round_keys}"}},'
        )
    lines.extend(["};", ""])
    output.write_text("\n".join(lines))
    gcm_output = args.output_dir / "gcm_vectors.h"
    gcm_lines = [
        "// Generated by tools/generate_harness_vectors.py; do not edit.",
        "#pragma once",
        "struct GcmVector {",
        "  const char *id; const char *key; const char *iv; const char *aad;",
        "  const char *input; const char *output; const char *tag; bool encrypt; bool auth;",
        "};",
        "static const GcmVector kGcmVectors[] = {",
    ]

    def append_case(item: dict[str, object], encrypting: bool, suffix: str) -> None:
        input_field = "plaintext" if encrypting else "ciphertext"
        output_field = "ciphertext" if encrypting else "plaintext"
        expected_output = str(item.get(output_field) or "")
        values = (
            f"{item['id']}-{suffix}", item["key"], item["iv"], item["aad"],
            item[input_field], expected_output, item["tag"],
        )
        quoted = ", ".join(f'"{value}"' for value in values)
        gcm_lines.append(f"  {{{quoted}, {'true' if encrypting else 'false'}, {'true' if item['expected_auth'] else 'false'}}},")

    for item in nist["gcm"]:
        append_case(item, item["direction"] == "encrypt", str(item["direction"]))
    for item in generated["positive"]:
        append_case(item, True, "encrypt")
        append_case(item, False, "decrypt")
    for item in generated["negative"]:
        append_case(item, False, "decrypt")
    gcm_lines.extend([
        "};",
        "",
        "static const GcmVector kPerformanceVectors[] = {",
    ])
    fixed_key = hashlib.sha256(b"aes-256-gcm-throughput-key-v1").digest()
    for iv_length in (12, 1):
        for aad_length in (0, 16, 64):
            for data_length in (0, 1, 15, 16, 17, 31, 32, 64):
                identifier = f"perf-iv{iv_length}-aad{aad_length}-data{data_length}"
                iv = hashlib.sha256((identifier + "-iv").encode()).digest()[:iv_length]
                aad = bytes((index * 5 + aad_length) & 0xFF for index in range(aad_length))
                plaintext = bytes((index * 11 + data_length) & 0xFF for index in range(data_length))
                ciphertext, tag = encrypt(fixed_key, iv, plaintext, aad)
                item = {
                    "id": identifier,
                    "key": fixed_key.hex(),
                    "iv": iv.hex(),
                    "aad": aad.hex(),
                    "plaintext": plaintext.hex(),
                    "ciphertext": ciphertext.hex(),
                    "tag": tag.hex(),
                    "expected_auth": True,
                }
                append_case(item, True, "encrypt")
                append_case(item, False, "decrypt")
    gcm_lines.extend(["};", ""])
    gcm_output.write_text("\n".join(gcm_lines))
    print(f"wrote {output} and {gcm_output} ({len(gcm_lines) - 9} GCM operations)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
